apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-whoami
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mint-cocoa/iouring-runtime.git
    targetRevision: main
    path: deploy/k8s/home/demo-whoami
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
